## STARTUP
#
exec-once = waybar -c .config/waybar/config-hypr &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = xhost +SI:localuser:root &
exec-once = bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown" &
exec-once = waypaper --restore
exec-once = nm-applet --indicator &
exec-once = blueman-applet &
exec-once = ~/.dotfiles/suckless/.config/suckless/scripts/rclone.sh
exec-once = pCloud-Wrapper
exec-once = xrdb ~/.Xresources &
exec-once = wl-paste --watch cliphist store &
exec-once = mako &
exec-once = udiskie &
# exec-once = dropbox &
# exec-once = ~/.azotebg-hyprland &
# exec-once = ~/.config/hypr/scripts/gtk-themes.sh
# exec-once = ~/.config/hypr/scripts/gtkthemes.sh
# exec-once = ~/.config/hypr/scripts/set-gtk-settings.sh
# exec-once = swww-daemon
# exec-once = swww img ~/.config/hypr/bg/world.png --transition-type center
# exec-once = swaybg -o \* -i ~/.config/hypr/bg/world.png -m fill
# exec-once = waypaper --restore
# exec-once = ~/.config/hypr/scripts/gtkthemes.sh # set gtkthemes
# exec-once = systemctl --user start hyprpolkitagent
# exec-once = fcitx5 -d &
